version: "3.7"

volumes:
  MONGO_DATA:

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - MONGO_DATA:/data/db
    ports:
      - 27017:27017 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo_ex
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=example


